// Para requisições com body:
// Content-Type: application/json 
// Pule 1 linha
// {}

// Para requisições com headers: 
// Authorization: "token"


###  // endpoint buscar atores
get http://localhost:3003/Users/005
####
GET http://localhost:3003/Users/Kenny
####
get http://localhost:3003/Users?gender=female
####
get http://localhost:3003/Users/search?gender=female
####
get http://localhost:3003/Users/nomes?name=Kenny
####
get http://localhost:3003/Users

###  // endpoint editar ator
PUT http://localhost:3003/Users/Fernanda
Content-Type: application/json 

{
 "salary": 5000000000
}

###  // endpoint deletar ator
DELETE http://localhost:3003/User/003

